name: Build Android

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build-android
    runs-on: ubuntu-latest
    steps:
      - name: Setup ssh key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.GITLAB_TOKEN }}
      - name: Checkout Repository
        env:
          GIT_SSH_COMMAND: ssh -o StrictHostKeyChecking=no -o ProxyCommand="ssh -o StrictHostKeyChecking=no ${{ vars.PROXY_USERNAME }}@${{ vars.PROXY_DOMAIN }} -p ${{ vars.PROXY_PORT }} -W %h:%p"
        run: |
          git clone --single-branch --depth 1 -b jiexun ${{ vars.GITLAB_REPOSITORY }} release
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
          check-latest: true
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.22.2
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:" # optional, change this to force refresh cache
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:" # optional, change this to specify the cache path
          pub-cache-key: "flutter-pub:os:-:channel:-:version:-:arch:-:hash:" # optional, change this to force refresh cache of dart pub get dependencies
          pub-cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:" # optional, change this to specify the cache path
      - name: Build
        working-directory: release
        run: |
          flutter pub get;
          flutter build apk --target-platform android-arm,android-arm64 --obfuscate --split-debug-info=./symbols
      - name: Install Rop
        run: npm -g install @sevenvip666/rop@latest
      - name: Upload
        working-directory: release
        run: rop upload android universal --accessKey ${{ secrets.ROP_ACCESS_KEY }}
