name: Build Android

on:
  push:
    branches:
      - test

jobs:
  build:
    name: build-android
    runs-on: ubuntu-latest
    steps:
      - name: Setup ssh key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.GITLAB_TOKEN }}
      - name: Checkout Repository
        env:
          GIT_SSH_COMMAND: ssh -o StrictHostKeyChecking=no -o ProxyCommand="ssh -o StrictHostKeyChecking=no ${{ vars.PROXY_USERNAME }}@${{ vars.PROXY_DOMAIN }} -p ${{ vars.PROXY_PORT }} -W %h:%p"
        run: |
          git clone --single-branch --depth 1 -b jiexun ${{ vars.GITLAB_REPOSITORY }} release
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
          check-latest: true
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.22.2
          cache: true
      - name: Pub Get
        working-directory: release
        run: flutter pub get
      - name: Build
        working-directory: release
        run: flutter build apk --target-platform android-arm64

